//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVCEntities : DbContext
    {
        public MVCEntities()
            : base("name=MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> students { get; set; }
    
        public virtual int sp_stinsert(string sna, Nullable<int> sag, string saddr)
        {
            var snaParameter = sna != null ?
                new ObjectParameter("sna", sna) :
                new ObjectParameter("sna", typeof(string));
    
            var sagParameter = sag.HasValue ?
                new ObjectParameter("sag", sag) :
                new ObjectParameter("sag", typeof(int));
    
            var saddrParameter = saddr != null ?
                new ObjectParameter("saddr", saddr) :
                new ObjectParameter("saddr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_stinsert", snaParameter, sagParameter, saddrParameter);
        }
    }
}
