//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Sid { get; set; }
        public string Sname { get; set; }
        public Nullable<int> Sage { get; set; }
        public string Saddress { get; set; }
    }
}
